{{- if .Values.metricsServer.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: metrics-server
---
# Permissions metrics-server needs to talk to the kubelet and read objects
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-metrics-server
  labels:
    app: metrics-server
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/stats
      - nodes/metrics
      - nodes/proxy
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-server
  labels:
    app: metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-metrics-server
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: {{ .Release.Namespace }}
---
# Allow metrics-server to read the requestheader CA config from kube-system
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-server-auth-reader
  namespace: kube-system
  labels:
    app: metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: {{ .Release.Namespace }}
---
# Delegated auth (commonly present in upstream installs)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-server-auth-delegator
  labels:
    app: metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: metrics-server
spec:
  selector:
    app: metrics-server
  ports:
    - name: https
      port: 443
      targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: metrics-server
spec:
  replicas: {{ .Values.metricsServer.replicas }}
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
    spec:
      serviceAccountName: metrics-server
      containers:
        - name: metrics-server
          image: {{ .Values.metricsServer.image | quote }}
          imagePullPolicy: IfNotPresent
          args:
{{- range .Values.metricsServer.args }}
            - {{ . | quote }}
{{- end }}
          ports:
            - name: https
              containerPort: 4443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: https
              scheme: HTTPS
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app: metrics-server
spec:
  group: metrics.k8s.io
  version: v1beta1
  service:
    name: metrics-server
    namespace: {{ .Release.Namespace }}
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

{{- end }}