apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
spec:
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: portainer/portainer-ce:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-service
spec:
  type: NodePort
  selector:
    app: portainer
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30004